language: php
php:
  - 5.5.9
  - 5.6
  - 7.0
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer require satooshi/php-coveralls:dev-master
script: phpunit
after_script:
  - php vendor/bin/coveralls -v
notifications:
  slack:
    secure: RT74mL1gnBhESLq+EXoFlgWXmUKC+gg7R6rLBvA8MVslf71ntmVXURC//K1JpP91Oi6jVmIT+1vJTSy4egH2CZkU0v4vGp8OlB+YTgT/OBJ/c7I228EIsA+5cjljF/nKzhBBkx+hnmU4J/kcBbN1MErY9W4yCwo8gDsaQ0CzGFQ7M/dTkRR0gvaIIBDr10BQfIVR3dP6zJurEFBNj3/Hn0KOH5cgJ+8VOaPgMeBDyMi4RxUVplgrEaRw07Y68L0e2TyLEZkIRMj7rEnRcb7//hdash86MZPVfJ069ENcClShFbrcLC2jKmk2iX9ONf1IH2pZtfMiZIQg+s1WJRGNqajEsrrndXF9q9N4ZhCzPADGGzHqo2koibEjgW3b8Wk0Q0K6hx20o67yL4S78uSXG2tuvqISVOs/VLwxXnr7uXBHsurNnaYVbRQr/mPvig80+Nfypgq2irQqouF51rhnYH98ysOifO87sthQ475srhK+FpH3/QIWVcDvEDaJMlPT4RqhKdBudE8SveLyLTUvDZ1jDqdcyF67q4PTP/evxowbiQpopS047WZa2W19kkx+Mb6Nw8qJ5zHyzQBustW1Y0Nq+Epx4RdXw3yIn6OmmYP4NKINY/BdfCM7eOLZ1Smj54baVHaxEtUrPGQoZ6ioklb7pfZGQ/TitFAQb9I5rCs=
